## let's see what is drifting and how ks_2samp works

In [1]:
import pandas as pd
import numpy as np

from scipy.stats import ks_2samp

In [2]:
d1 = np.arange(10)  ## say train data
d2 = np.arange(10)   ## say test data

In [3]:
d1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
d2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
test = ks_2samp(d1,d2)
test

KstestResult(statistic=0.0, pvalue=1.0, statistic_location=0, statistic_sign=1)

## Data drift:

* set we set threshold of p_value = 0.5

* If the p_value is greater than or qual to 0.5 then there is no drift in the data. If the p_value is less than the threshold(0.5 here) then there is a drift in the train and test data.

* since p_vlaue is 1.0>0.5 --> no drift

In [7]:
d3 = np.arange(10)
d4 = np.arange(100)

In [8]:
d3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
d4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [11]:
test = ks_2samp(d3,d4)
test

KstestResult(statistic=0.9, pvalue=7.88295587183084e-09, statistic_location=9, statistic_sign=1)

In [8]:
from sensor.utils.main_utils import read_yaml_file

for reading the .env file
for reading the .env file
